title: Ryan's Blog
description: "A collection of thoughts about stuff."
author:
  name: "Ryan Steel"
  email: "rsteel1@protonmail.com"
  url: "https://ryansteel.co.uk"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Ryan Steel"
year : "2020"
